{
 "title": "Windows Server Graphs",
 "description": "Windows Host Monitoring using node-exporter",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - windows_system_boot_time_timestamp{fqdn=~\"$fqdn\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (fqdn) (irate(windows_cpu_time_total{mode=\"idle\", fqdn=~\"$fqdn\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU Modes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum by (mode) (rate(windows_cpu_time_total{fqdn=~\"$fqdn\"}[5m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{mode}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_memory_physical_total_bytes{fqdn=~\"$fqdn\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Physical memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "windows_memory_physical_free_bytes{fqdn=~\"$fqdn\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Free physical memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "windows_memory_available_bytes{fqdn=~\"$fqdn\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Available memory",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Processors",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_cpu_logical_processor{fqdn=~\"$fqdn\"}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(windows_memory_physical_total_bytes{fqdn=~\"$fqdn\"} - windows_memory_physical_free_bytes{fqdn=~\"$fqdn\"}) / windows_memory_physical_total_bytes{fqdn=~\"$fqdn\"} * 100"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_memory_physical_free_bytes{fqdn=~\"$fqdn\"}"
    }
   ]
  },
  {
   "title": "C: Disk Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(windows_logical_disk_size_bytes{volume=\"C:\", fqdn=~\"$fqdn\"}) by (fqdn) - sum(windows_logical_disk_free_bytes{volume=\"C:\", fqdn=~\"$fqdn\"}) by (fqdn)) / sum(windows_logical_disk_size_bytes{volume=\"C:\", fqdn=~\"$fqdn\"}) by (fqdn) * 100"
    }
   ]
  },
  {
   "title": "D: Disk",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(windows_logical_disk_size_bytes{volume=\"D:\", fqdn=~\"$fqdn\"}) by (fqdn) - sum(windows_logical_disk_free_bytes{volume=\"D:\", fqdn=~\"$fqdn\"}) by (fqdn)) / sum(windows_logical_disk_size_bytes{volume=\"D:\", fqdn=~\"$fqdn\"}) by (fqdn) * 100"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "windows_system_processes{fqdn=~\"$fqdn\"}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(windows_net_bytes_total{fqdn=~\"$fqdn\"}[5m])) / sum(windows_net_current_bandwidth_bytes{fqdn=~\"$fqdn\"}/8) * 100"
    }
   ]
  },
  {
   "title": "Network Bytes - Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(windows_net_bytes_received_total{fqdn=~\"$fqdn\"}[$interval])",
     "legendFormat": "Received Total:  {{nic}}"
    },
    {
     "expr": "- irate(windows_net_bytes_sent_total{fqdn=~\"$fqdn\"}[$interval])",
     "legendFormat": "Sent Total:  {{nic}}"
    }
   ]
  },
  {
   "title": "Disk Free",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_logical_disk_free_bytes{fqdn=~\"$fqdn\", volume !~\"HarddiskVolume.+\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "System Threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_system_threads{fqdn=~\"$fqdn\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "TCP Connections Active Total (ipv4)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(windows_tcp_connections_active_total{fqdn=~\"$fqdn\", af=\"ipv4\"}[1m])"
    }
   ]
  },
  {
   "title": "Network Packets - Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_packets_received_total{fqdn=~\"$fqdn\"}[$interval])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Received Total:  {{nic}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "- irate(windows_net_packets_sent_total{fqdn=~\"$fqdn\"}[$interval])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Sent Total:  {{nic}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Hard disk i/o ops total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_logical_disk_split_ios_total{fqdn=~\"$fqdn\", volume !~\"HarddiskVolume.+\"}[30s])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "System exception dispatches",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_system_exception_dispatches_total{fqdn=~\"$fqdn\"}[$interval])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "TCP Connections Passive Total (ipv4)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(windows_tcp_connections_passive_total{fqdn=~\"$fqdn\", af=\"ipv4\"}[1m])"
    }
   ]
  },
  {
   "title": "Network Packets - Received Discarded / Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_packets_received_errors_total{fqdn=~\"$fqdn\"}[$interval])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Received Errors Total: {{nic}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_packets_received_discarded_total{fqdn=~\"$fqdn\"}[$interval])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Received Discarded Total:  {{nic}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_write_bytes_total{fqdn=~\"$fqdn\", volume !~\"HarddiskVolume.+\"}[30s])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Write {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "- irate(windows_logical_disk_read_bytes_total{fqdn=~\"$fqdn\", volume !~\"HarddiskVolume.+\"}[30s])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Read {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "TCP Connections Established (ipv4)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(windows_tcp_connections_established{fqdn=~\"$fqdn\", af=\"ipv4\"}[1m])"
    }
   ]
  },
  {
   "title": "Network Packets - Outbound Discarded / Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_packets_outbound_errors_total{fqdn=~\"$fqdn\"}[$interval])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Outbound Errors Total:  {{nic}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_packets_outbound_discarded_total{fqdn=~\"$fqdn\"}[$interval])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Outbound Discarded Total:  {{nic}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Services by state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(windows_service_state{fqdn=~\"$fqdn\"}) by (state)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{state}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  }
 ]
}