<#
.SYNOPSIS
    Sets the client TLS protocols to use TLS 1.2 or higher.

.DESCRIPTION
    This function sets the client TLS protocols to use TLS 1.2 or higher by including all available protocols that are TLS 1.2 or higher.

.PARAMETER None
    This function does not take any parameters.

.OUTPUTS
    No output is generated by this function.

.EXAMPLE
    PS> Set-ClientTlsProtocols

.NOTES
    Author: klee-it
    PowerShell Version: 5.1, 7.x
#>

###
### FUNCTION: set client tls protocols
###
Function Set-ClientTlsProtocols
{
    [OutputType([System.Management.Automation.PSObject])]
    [CmdLetBinding(DefaultParameterSetName="Default")]

    param()
    
    # set function parameters
    try
    {
        # find and include all available protocols 'Tls12' or higher
        $AvailableTls = [enum]::GetValues('Net.SecurityProtocolType') | Where-Object { $_ -ge 'Tls12' }
    
        $AvailableTls.ForEach({
            [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor $_
        })
    }
    catch
    {
        Write-Error "[$($_.InvocationInfo.ScriptLineNumber)] $($_.Exception.Message)"
    }
}
